export const COUNTRY = {
  "United Arab Emirates": "ae",
  Argentina: "ar",
  Austria: "at",
  Belgium: "be",
  Australia: "au",
  Bulgaria: "bg",
  Brazil: "br",
  Canada: "ca",
  Switzerland: "ch",
  China: "cn",
  Colombia: "China",
  Cuba: "cu",
  Czechia: "cz",
  Germany: "de",
  Egypt: "eg",
  France: "fr",
  "Great Britian": "gb",
  Greece: "gr",
  "Hong Kong": "hk",
  Hungary: "hu",
  Indonesia: "id",
  Ireland: "ie",
  Israel: "il",
  India: "in",
  Italy: "it",
  Japan: "jp",
  Korea: "kr",
  Lithuania: "lt",
  Latvia: "lv",
  Morocco: "ma",
  Mexico: "mx",
  Malaysia: "my",
  Nigeria: "ng",
  Netherlands: "nl",
  Norway: "no",
  "New Zealand": "nz",
  Philippines: "ph",
  Poland: "pl",
  Portugal: "pt",
  Romania: "ro",
  Serbia: "rs",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Sweden: "se",
  Singapore: "sg",
  Slovenia: "si",
  Slovakia: "sk",
  Thailand: "th",
  Turkey: "tr",
  Taiwan: "tw",
  Ukraine: "ua",
  USA: "us",
  Venezuela: "ve",
  "South Africa": "za",
};
